#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_WIDTH 800.0f
#define WINDOW_HEIGHT 600.0f
#define TARGET_FPS 144

#define GRAVITY 980.f
#define MAX_VEL_X 0
#define MAX_VEL_Y 0
#define RANDOM_VEL_MAGNITUDE 500.f

#define UNIFORM_PARTITION_ROW 4
#define UNIFORM_PARTITION_COL 4

constexpr int ROW_INC((WINDOW_HEIGHT + UNIFORM_PARTITION_ROW - 1) / UNIFORM_PARTITION_ROW);
constexpr int COL_INC((WINDOW_WIDTH + UNIFORM_PARTITION_COL - 1) / UNIFORM_PARTITION_COL);

#endif  // CONSTANTS_HPP
