#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define WINDOW_WIDTH 800.0f
#define WINDOW_HEIGHT 600.0f
#define TARGET_FPS 100000

#define GRAVITY 980.f
#define MAX_VEL_X 0
#define MAX_VEL_Y 0

#define UNIFORM_PARTITION_ROW 2
#define UNIFORM_PARTITION_COL 2

#endif  // CONSTANTS_HPP
